config/routes.rb
Rails.application.routes.draw do
  resources :bees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bee.rb
class Bee < ApplicationRecord
  geocoded_by :address 
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bees_controller.rb
class BeesController < ApplicationController

  def index
    @bees = Bee.all
  end

  def new
    @bee = Bee.new
  end

  def create
    @bee = Bee.new(bees_params)
    if @bee.save
      redirect_to @bee
    else
      render "new"
    end    
  end

  def show 
    @bee = Bee.find(params[:id])
  end

  def destroy
    @bee = Bee.find(params[:id])
    @bee.destroy
    redirect_to @bee
  end

  def edit
    @bee = Bee.find(params[:id])
  end

  def update
    @bee = Bee.find(params[:id])
    @bee.update(bees_params)
    redirect_to @bee
  end

  private

  def bees_params
    params.require(:bee).permit(:name, :address, :bee_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bees_helper.rb
module BeesHelper
end

app/views/bees/_bee_form.html.erb
<%=form_for @bee do |f|%>
<%=f.label :name%>
<%=f.text_field :name%>
<%=f.label :bee_type%>
<%=f.text_field :bee_type%>
<%=f.label :address, "Where are the bees"%>
<%=f.text_field :address%>
<%=f.submit "submit"%>
<%end%>

app/views/bees/edit.html.erb
<%=render "bee_form"%>

app/views/bees/index.html.erb
<% @bees.each.with_index(1) do |bee,i| %>
<%="#{i}:#{bee.name} #{bee.bee_type}"%><br>
<%end%>

app/views/bees/new.html.erb
<%=render "bee_form"%>

app/views/bees/show.html.erb
<%=@bee.name%>
<%=@bee.bee_type%>
<%=link_to "Edit", edit_bee_url%>
<%=link_to "Delete", bee_url(@bee), method: :delete%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>